/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.fibd;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class RecpaytypeVO extends SuperVO {
	private java.lang.String pk_recpaytype;
	private java.lang.String pk_org;
	private java.lang.String name;
	private java.lang.String name2;
	private java.lang.String name3;
	private java.lang.String name4;
	private java.lang.String name5;
	private java.lang.String name6;
	private java.lang.String code;
	private java.lang.Integer pretype;
	private nc.vo.pub.lang.UFBoolean issettle;
	private nc.vo.pub.lang.UFBoolean issystem;
	private java.lang.Integer enablestate;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_group;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_RECPAYTYPE = "pk_recpaytype";
	public static final String PK_ORG = "pk_org";
	public static final String NAME = "name";
	public static final String NAME2 = "name2";
	public static final String NAME3 = "name3";
	public static final String NAME4 = "name4";
	public static final String NAME5 = "name5";
	public static final String NAME6 = "name6";
	public static final String CODE = "code";
	public static final String PRETYPE = "pretype";
	public static final String ISSETTLE = "issettle";
	public static final String ISSYSTEM = "issystem";
	public static final String ENABLESTATE = "enablestate";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_GROUP = "pk_group";
	
	//add chenth 20161206 新加坡盛大项目增加“是否手续费”字段 
	//add by weiningc 20171012 V633适配至V65 start
	private nc.vo.pub.lang.UFBoolean isbankcharges;	
	public static final String ISBANKCHARGES = "isbankcharges";	
	public nc.vo.pub.lang.UFBoolean getIsbankcharges() {
		return isbankcharges;
	}
	public void setIsbankcharges(nc.vo.pub.lang.UFBoolean isbankcharges) {
		this.isbankcharges = isbankcharges;
	}
	//add end
	//add by weiningc 20171012 V633适配至V65 end
			
	/**
	 * 属性pk_recpaytype的Getter方法.属性名：收付款类型标识
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_recpaytype () {
		return pk_recpaytype;
	}   
	/**
	 * 属性pk_recpaytype的Setter方法.属性名：收付款类型标识
	 * 创建日期:
	 * @param newPk_recpaytype java.lang.String
	 */
	public void setPk_recpaytype (java.lang.String newPk_recpaytype ) {
	 	this.pk_recpaytype = newPk_recpaytype;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性name2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName2 () {
		return name2;
	}   
	/**
	 * 属性name2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName2 java.lang.String
	 */
	public void setName2 (java.lang.String newName2 ) {
	 	this.name2 = newName2;
	} 	  
	/**
	 * 属性name3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName3 () {
		return name3;
	}   
	/**
	 * 属性name3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName3 java.lang.String
	 */
	public void setName3 (java.lang.String newName3 ) {
	 	this.name3 = newName3;
	} 	  
	/**
	 * 属性name4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName4 () {
		return name4;
	}   
	/**
	 * 属性name4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName4 java.lang.String
	 */
	public void setName4 (java.lang.String newName4 ) {
	 	this.name4 = newName4;
	} 	  
	/**
	 * 属性name5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName5 () {
		return name5;
	}   
	/**
	 * 属性name5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName5 java.lang.String
	 */
	public void setName5 (java.lang.String newName5 ) {
	 	this.name5 = newName5;
	} 	  
	/**
	 * 属性name6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName6 () {
		return name6;
	}   
	/**
	 * 属性name6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName6 java.lang.String
	 */
	public void setName6 (java.lang.String newName6 ) {
	 	this.name6 = newName6;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性pretype的Getter方法.属性名：收付款性质
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.Integer getPretype () {
		return pretype;
	}   
	/**
	 * 属性pretype的Setter方法.属性名：收付款性质
	 * 创建日期:
	 * @param newPretype java.lang.String
	 */
	public void setPretype (java.lang.Integer newPretype ) {
	 	this.pretype = newPretype;
	} 	  
	/**
	 * 属性issettle的Getter方法.属性名：现金结算
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIssettle () {
		return issettle;
	}   
	/**
	 * 属性issettle的Setter方法.属性名：现金结算
	 * 创建日期:
	 * @param newIssettle nc.vo.pub.lang.UFBoolean
	 */
	public void setIssettle (nc.vo.pub.lang.UFBoolean newIssettle ) {
	 	this.issettle = newIssettle;
	} 	  
	/**
	 * 属性issystem的Getter方法.属性名：系统预置
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIssystem () {
		return issystem;
	}   
	/**
	 * 属性issystem的Setter方法.属性名：系统预置
	 * 创建日期:
	 * @param newIssystem nc.vo.pub.lang.UFBoolean
	 */
	public void setIssystem (nc.vo.pub.lang.UFBoolean newIssystem ) {
	 	this.issystem = newIssystem;
	} 	  
	/**
	 * 属性enablestate的Getter方法.属性名：启用状态
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEnablestate () {
		return enablestate;
	}   
	/**
	 * 属性enablestate的Setter方法.属性名：启用状态
	 * 创建日期:
	 * @param newEnablestate java.lang.Integer
	 */
	public void setEnablestate (java.lang.Integer newEnablestate ) {
	 	this.enablestate = newEnablestate;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_recpaytype";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "fi_recpaytype";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "fi_recpaytype";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public RecpaytypeVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.fibd.RecpaytypeVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


